name: Build Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Runs on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd ./Private && cargo build --verbose
    - name: Run tests
      run: cd ./Private && cargo test --verbose
